# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded xoSAML 0.1 [list source [file join $dir xoSAML.xotcl]]
package ifneeded xoSAML::Bindings 0.1 [list source [file join $dir Bindings.xotcl]]
package ifneeded xoSAML::Objects 0.1 [list source [file join $dir Objects.xotcl]]
package ifneeded xoSAML::Schema 0.1 [list source [file join $dir "generated" Schema.xotcl]]
package ifneeded xoSAML::Environment 0.1 [list source [file join $dir "generated" Environment.xotcl]]
package ifneeded xoSAML::Http::Client 0.1 [list source [file join $dir HttpClient.xotcl]]
